# Generated by Django 3.0.2 on 2020-06-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('assuntos', models.CharField(max_length=200)),
                ('texto_postagem', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criada em')),
                ('data_modificacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizada em')),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
    ]
