# Generated by Django 3.0.7 on 2020-06-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
