# Generated by Django 3.0.2 on 2020-05-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Receita'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='imagem'),
        ),
    ]
