# Generated by Django 3.0.2 on 2020-05-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0002_auto_20200506_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='receitas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Palavra-chave'),
        ),
    ]
