# Generated by Django 3.0.2 on 2020-05-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0003_auto_20200506_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receitas',
            options={'ordering': ['update_at'], 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
    ]
