# Generated by Django 3.0.7 on 2020-06-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0004_auto_20200507_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='disclaimer',
            field=models.TextField(default='Receita prática e nutritiva.', verbose_name='Resumo'),
        ),
    ]
