# Generated by Django 3.0.7 on 2020-06-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0005_receitas_disclaimer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='description',
        ),
        migrations.AddField(
            model_name='receitas',
            name='ingredientes',
            field=models.TextField(blank=True, null=True, verbose_name='Ingredientes'),
        ),
        migrations.AddField(
            model_name='receitas',
            name='modo_preparo',
            field=models.TextField(null=True, verbose_name='Modo de Preparo'),
        ),
    ]
