# Generated by Django 3.0.2 on 2020-06-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0006_auto_20200608_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagem'),
        ),
    ]
